---
- name: Create Seperate Partition for /tmp
  debug: 
     msg: "Manually Create Seperate Partition for /tmp"
  tags:
    - "1.1.2"
- name: Create Volume 
  ec2_vol:
     aws_access_key: ""
     aws_secret_key: ""
     instance: "{{ item }}"
     volume_size: "5"
     device_name: /dev/xvdf
     region: 'us-east-1' 
     volume_type: gp2
  register: ec2_vol
  with_items:
       - 3.81.117.60
  tags: volume

- name: Printing the volume information
  debug: 
      var: ec2_vol

- name: gathering ec instance information
  ec2_instance_info:
      aws_access_key: ""
      aws_secret_key: ""
      region: 'us-east-1'
  register: ec2_instance_info
  tags:
    - info

- name: printing the instance info
  debug:
     msg: "{{ ec2_instance_info.instances[0].instance_id}}"
  tags:
    - info
